name: Daily Push to GitHub

on:
  schedule:
    - cron: '0 18 * * *'

jobs:
  push-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Commit changes
        run: |
          git config --global user.name "willzhou109"
          git config --global user.email "willzhou109@gmail.com"
          git add .
          git commit -m "Daily NBA update"

      - name: Push changes to GitHub
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
